spring:
  datasource:
#    url:  jdbc:postgresql://${DB_HOST}/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driverClassName: org.postgresql.Driver
    url: jdbc:h2:./db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true